### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by maitreyastark** [tatsuyah/Keras-CNN-Image-Classifier#2]
I get this error when trying to train a multiclass model:

"""
train-multiclass.py:125: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras.pre..., epochs=20, validation_data=<keras.pre..., callbacks=[<keras.ca..., validation_steps=300, steps_per_epoch=0)`
  validation_steps=validation_steps)
Epoch 1/20
Traceback (most recent call last):
  File "train-multiclass.py", line 125, in <module>
    validation_steps=validation_steps)
  File "/Users/maitreyasatavalekar/anaconda/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/maitreyasatavalekar/anaconda/lib/python3.6/site-packages/keras/models.py", line 1276, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/maitreyasatavalekar/anaconda/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/maitreyasatavalekar/anaconda/lib/python3.6/site-packages/keras/engine/training.py", line 2262, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Users/maitreyasatavalekar/anaconda/lib/python3.6/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/Users/maitreyasatavalekar/anaconda/lib/python3.6/site-packages/keras/callbacks.py", line 339, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'
"""
what should i do?

**Comment by ghost** [comment]
Same warning occurring in mine too.
What i am supposed to do ?

**Comment by maitreyastark** [comment]
I worked with a different training model.... use this for reference https://pythonprogramming.net/convolutional-neural-network-kats-vs-dogs-machine-learning-tutorial/
You can read comments for adding more classes in order to make it a multiclass model

**Comment by ghost** [comment]
Yes.Thank You for replying.I got my desired output.
Have you ever worked on CNN based classification on a video ?

**Comment by sunaina123** [comment]
Someone help me please, I am not able to predict the outputs because after training models.h5 and models.weights.h5 are not generated.
