### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by RAMIREDDYDEVARAM** [tatsuyah/Keras-CNN-Image-Classifier#3]

**Comment by RAMIREDDYDEVARAM** [comment]
Epoch 1/20
31/31 [==============================] - 198s 6s/step - loss: 5.4380 - acc: 0.0806 - val_loss: 2.9033 - val_acc: 0.1187
Traceback (most recent call last):
  File "train1.py", line 125, in <module>
    validation_steps=validation_steps)
  File "/home/ram/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ram/.local/lib/python3.5/site-packages/keras/models.py", line 1276, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ram/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ram/.local/lib/python3.5/site-packages/keras/engine/training.py", line 2262, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ram/.local/lib/python3.5/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ram/.local/lib/python3.5/site-packages/keras/callbacks.py", line 820, in on_epoch_end
    raise ValueError('If printing histograms, validation_data must be '
ValueError: If printing histograms, validation_data must be provided, and cannot be a generator.

**Comment by sunaina123** [comment]
same error is mine

**Comment by RAMIREDDYDEVARAM** [comment]
I solved it. just replace Histogram_freq =0 instead Histogram_freq = 10 or 1

**Comment by sunaina123** [comment]
Thanku

**Comment by RAMIREDDYDEVARAM** [comment]
If I see your code I can help you

**Comment by sunaina123** [comment]
yeah sure

**Comment by sunaina123** [comment]
please help me

**Comment by RAMIREDDYDEVARAM** [comment]
how can we understand without your code. we have to see your code.
copy and past here your code
then which error you got. than easy to find problem

**Comment by sunaina123** [comment]
outputs are not showing correct.... sometimes only tp,TN shown and
sometimes only fn,fp not altogether

**Comment by czainab** [comment]
@RAMIREDDYDEVARAM  I am able to run the test file but my predict file is not giving output
True Positive AD:  0
True Negative AD:  0
False Positive Normal:  0
False Negative Normal:  0
Traceback (most recent call last):
  File "predict-binary.py", line 62, in <module>
    precision = tp / (tp + fp)
ZeroDivisionError: division by zero
Infact I had trained my model and save it and it's giving  accuracy around 97%

**Comment by sunaina123** [comment]
same problem is mine.

**Comment by czainab** [comment]
Are you able to solve this problem?

Sent from Yahoo Mail on Android 
 
  On Thu, 24 May, 2018 at 9:00 AM, sunaina123<notifications@github.com> wrote:   same problem is mine.
